### ISSUE TITLE
Not able to parse GC logs with `-verbose:gc -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps`

### ISSUE THREAD

**Issue by klauern** [linkedin/JTune#6]
When I run `jtune.py` with some GC logs that I have created previously, I get this output:

     $ python jtune.py -r mygc.log
    2015-04-15 12:39:40,439: "root" (line: 1858) - ERROR I was not able to read the replay file. Exiting.

I have a set of JVM's that I am already using GC logging for, but I am unable to have JTune parse the log files.  The following are the GC log settings I have in place already:

`-verbose:gc -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps`

It may be due to the difference between what `-XX:+PrintGCDateStamps` provides versus the default time output, or something that `-verbose:gc` is doing already.

**Comment by ericbullen** [comment]
jtune will find the log files based on information it sees on the command-line for the pid you give it. The '-r' option is for the replay file, not the gc.log file. The replay file is automatically saved so that you can do further analysis on it on another host/time if you want.

**Comment by klauern** [comment]
Ah, that makes sense now.  Unfortunately, I will have to spend some time to get this working on my servers, but at least I know this won't work with my GC logs.

**Comment by sinel** [comment]
I apologize if this is the wrong place to ask my question, but I am adding it here since I think it is relevant to this topic. We have an automated performance testing setup where our application is running within a docker container, and both the docker container and the EC2 server where it is hosted has a lifetime spanning the test duration only. We are collecting logs to a centralized location and we are using -verbose:gc. We would really like to use jtune to analyze these results, and we were hoping to filter the logs and collect all the gc information in a separate file, which we would use as input to jtune.

From this thread, I understand that this is not supported. Is there any work around or suggested approach for this case? I would imagine that there would be many people who want to analyze the logs after the test instead of during it, due to constraints such as ours or concerns with regard to adding another process in the mix.

Thanks...

**Comment by klauern** [comment]
I'm not the developer for it, but I can say that at least in looking at the code here: https://github.com/linkedin/JTune/blob/master/jtune.py#L1519-L1532 , you will notice that JTune will need a couple runs of `jstat` in order to function properly.  Since that information isn't provided natively from the GC logs, it wouldn't be possible to inspect them without more context behind the runtime of the JVM that you're inspecting

**Comment by sinel** [comment]
@klauern Thanks for the insight. I don't know python, so I hadn't tried looking at the code. That's too bad. I think it would have been really handy to use it for post-analysis.

**Comment by ericbullen** [comment]
klauren is correct. Currently jtune needs to run inline during the profiling. I have an internal version of jtune that doesn't need jstat, and can read gc logs for everything, but it's not ready yet. I'd expect to release it in a few weeks.

**Comment by sinel** [comment]
@ericbullen that's great! it will be too late for our current cycle of tests, but I will definitely try using it for the next. thanks for the quick response.
